### ISSUE TITLE
TEST: This is only a test.

### ISSUE THREAD

**Issue by stscijgbot-jp** [eslavich/jirahub-sandbox-ii#17]
_Issue [JP-1398](https://jira-test.stsci.edu/browse/JP-1398) was created on JIRA by [Howard Bushouse](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

This is only a test. For the next 2 sentences the Jira ticket maintainers in your project will be conducting a test of the new Jira<->Github bot system. Had this been a real issue, you would be assigned to complete this task and instructed to do so from the shelter of your home.

**Comment by hbushouse** [comment]
Adding a comment to the GitHub issue. Let's see if it shows up in the Jira ticket.

**Comment by hbushouse** [comment]
Adding a comment that contains github-specific markup, such as a pipeline name like `calwebb_image2` and a step class name like `DarkCurrentStep`. Let's see what that looks like in the Jira ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira-test.stsci.edu/browse/JP-1398?focusedCommentId=456673#comment-456673):_

(y)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira-test.stsci.edu/browse/JP-1398?focusedCommentId=456675#comment-456675):_

Let's see what happens on the GitHub side when I resolve the Jira ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira-test.stsci.edu/browse/JP-1398?focusedCommentId=456676#comment-456676):_

It's dead .... err, done Jim.
